
package br.gov.sp.prefeitura.nfe;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LoteNFe", targetNamespace = "http://www.prefeitura.sp.gov.br/nfe", wsdlLocation = "file:/C:/jason/work/atividades/crawler_notarj/prefeitura_sp/lotenfe.xml")
public class LoteNFe
    extends Service
{

    private final static URL LOTENFE_WSDL_LOCATION;
    private final static WebServiceException LOTENFE_EXCEPTION;
    private final static QName LOTENFE_QNAME = new QName("http://www.prefeitura.sp.gov.br/nfe", "LoteNFe");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
//            url = new URL("file:/C:/jason/work/atividades/crawler_nota/prefeitura_sp_stubs/lotenfe.xml");
        	URL base = LoteNFe.class.getProtectionDomain().getCodeSource().getLocation();
            url = new URL(base, "wsdl/lotenfe.xml");
            System.out.println("url:" + url);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOTENFE_WSDL_LOCATION = url;
        LOTENFE_EXCEPTION = e;
    }

    public LoteNFe() {
        super(__getWsdlLocation(), LOTENFE_QNAME);
    }

    public LoteNFe(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOTENFE_QNAME, features);
    }

    public LoteNFe(URL wsdlLocation) {
        super(wsdlLocation, LOTENFE_QNAME);
    }

    public LoteNFe(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOTENFE_QNAME, features);
    }

    public LoteNFe(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoteNFe(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LoteNFeSoap
     */
    @WebEndpoint(name = "LoteNFeSoap")
    public LoteNFeSoap getLoteNFeSoap() {
        return super.getPort(new QName("http://www.prefeitura.sp.gov.br/nfe", "LoteNFeSoap"), LoteNFeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoteNFeSoap
     */
    @WebEndpoint(name = "LoteNFeSoap")
    public LoteNFeSoap getLoteNFeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.prefeitura.sp.gov.br/nfe", "LoteNFeSoap"), LoteNFeSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns LoteNFeSoap
     */
    @WebEndpoint(name = "LoteNFeSoap12")
    public LoteNFeSoap getLoteNFeSoap12() {
        return super.getPort(new QName("http://www.prefeitura.sp.gov.br/nfe", "LoteNFeSoap12"), LoteNFeSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoteNFeSoap
     */
    @WebEndpoint(name = "LoteNFeSoap12")
    public LoteNFeSoap getLoteNFeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.prefeitura.sp.gov.br/nfe", "LoteNFeSoap12"), LoteNFeSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOTENFE_EXCEPTION!= null) {
            throw LOTENFE_EXCEPTION;
        }
        return LOTENFE_WSDL_LOCATION;
    }

}
